force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Number_of_Tickets__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Tickets__c</fullName>
    <label>Number of Tickets</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Attendee__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <referenceTo>Ticket_Type__c</referenceTo>
    <relationshipLabel>Attendees</relationshipLabel>
    <relationshipName>Attendees</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Banner_Image__c.field-meta.xml
<CustomField>
    <fullName>Banner_Image__c</fullName>
    <label>Banner Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Ticket_Type__c/Ticket_Type__c.object-meta.xml
<CustomObject>
    <label>Ticket Type</label>
    <nameField>
        <label>Ticket Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Ticket_Type__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Ticket Types</relationshipLabel>
    <relationshipName>Ticket_Types</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Ticket_Type__c/fields/Quantity_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Remaining__c</fullName>
    <formula>Total_Quantity__c  -  Quantity_Sold__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Remaining</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket_Type__c/fields/Quantity_Sold__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Sold__c</fullName>
    <label>Quantity Sold</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Ticket_Type__c/fields/Sale_Price__c.field-meta.xml
<CustomField>
    <fullName>Sale_Price__c</fullName>
    <description>sale price of the ticket</description>
    <label>Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/EventsController.cls
public with sharing class EventsController {

    @AuraEnabled(Cacheable=true)
    public static String getBannerImage(String eventId) {
        return [SELECT Id, Banner_Image__c FROM Event__c WHERE Id =: eventId].Banner_Image__c;
    }

    @AuraEnabled(Cacheable=true)
    public static List<TicketType> getTicketTypes(String eventId) {
        List<Ticket_Type__c> ticketTypes = [SELECT Id, Name, Description__c, Sale_Price__c, Quantity_Remaining__c FROM Ticket_Type__c WHERE Event__c = :eventId AND Is_Active__c = true];
        List<TicketType> wrappers = new List<TicketType>();
        for (Ticket_Type__c tt : ticketTypes) {
            TicketType wrapper = new TicketType();
            wrapper.name = tt.Name;
            wrapper.description = tt.Description__c;
            wrapper.salePrice = tt.Sale_Price__c;
            wrapper.quantity = tt.Quantity_Remaining__c;
            wrapper.id = tt.Id;
            wrapper.options = getOptions(Integer.valueOf(tt.Quantity_Remaining__c));
            wrappers.add(wrapper);
        }
        return wrappers;
    }

    public static List<Option> getOptions(Integer quantity) {
        List<Option> options = new List<Option>();
        for (Integer i=1; i<=quantity; i++) {
            options.add(new Option(String.valueOf(i), String.valueOf(i)));
        }
        return options;
    }

    @AuraEnabled
    public static Boolean createAttendee(String attendeeDetails) {
        Boolean isSuccess = false;
        Attendee att = (Attendee) JSON.deserialize(attendeeDetails, Attendee.Class);
        Attendee__c attRecord = new Attendee__c();
        attRecord.Name = att.name;
        attRecord.Event__c = att.eventId;
        attRecord.Ticket_Type__c = att.ticketTypeId;
        attRecord.Email__c = att.email;
        attRecord.Number_of_Tickets__c = Integer.valueOf(att.numberOfTickets);
        Ticket_Type__c tt = [SELECT Id, Quantity_Sold__c FROM Ticket_Type__c WHERE Id=:att.ticketTypeId];
        if (tt.Quantity_Sold__c == null) {
            tt.Quantity_Sold__c = 0;
        }
        tt.Quantity_Sold__c += Integer.valueOf(att.numberOfTickets);
        try {
            Database.insert(attRecord);
            Database.upsert(tt);
            isSuccess = true;
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
        return isSuccess;
    }

    public class TicketType {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public Decimal salePrice;
        @AuraEnabled
        public Decimal quantity;
        @AuraEnabled
        public String id;
        @AuraEnabled
        public List<Option> options;

    }

    public class Option {
        @AuraEnabled
        public String label;
        @AuraEnabled
        public String value;

        public Option (String label, String value) {
            this.label = label;
            this.value = value;
        }
    }

    public class Attendee {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String eventId;
        @AuraEnabled
        public String ticketTypeId;
        @AuraEnabled
        public String email;
        @AuraEnabled
        public Decimal numberOfTickets;
    }


}